'use client'

import { useState } from 'react'
import Link from 'next/link'
import { motion } from 'framer-motion'
import {
  AlertOctagon,
  AlertTriangle,
  Globe,
  Smartphone,
  Send,
  CreditCard,
  Clock,
  MapPin,
  CheckCircle2,
  ShieldAlert,
  Lock,
  ArrowRight,
  Info
} from 'lucide-react'
import { UserLayout } from '@/components/layout/user-layout'
import { MotionWordReveal, MotionFadeUp, MotionBadge } from '@/components/motion/animated-text'
import { SecurityActionModal, SecurityModalType } from '@/components/security/security-action-modal'

export default function UserAlertsPage() {
  const [resolvedIds, setResolvedIds] = useState<string[]>([])
  const [modalConfig, setModalConfig] = useState<{
    open: boolean
    type: SecurityModalType
    data: any
  }>({
    open: false,
    type: 'account_freeze',
    data: {}
  })
  const [inAppToast, setInAppToast] = useState<string | null>(null)

  const showToast = (msg: string) => {
    setInAppToast(msg)
    setTimeout(() => setInAppToast(null), 3500)
  }

  const handleAction = (id: string, actionName: string) => {
    setResolvedIds((prev) => [...prev, id])

    if (actionName === 'Account Frozen') {
      setModalConfig({
        open: true,
        type: 'account_freeze',
        data: {
          entityTitle: 'ALERT-101 (Delhi Concurrent Transfer)',
          location: 'Delhi, India',
          time: '2:18 AM',
          amount: '28,000',
          deviceId: 'New Android (DEV-A782)',
          ip: '49.36.128.91',
          reason: 'Deterministic firewall: 3 checks triggered (NEW_PAYEE_GUARD, NIGHT_SAFETY_WINDOW, FOREIGN_DEVICE_TRIGGER)'
        }
      })
    } else if (actionName === 'Card Frozen') {
      setModalConfig({
        open: true,
        type: 'card_freeze',
        data: {
          entityTitle: 'HDFC Regalia Visa (**** 4821)',
          location: 'Singapore (SG)',
          cardLast4: '4821',
          time: 'Today 11:42 AM',
          amount: '32,000',
          reason: 'Cross-Border foreign POS payment from Singapore without 3D Secure OTP'
        }
      })
    } else {
      showToast(`✓ Alert ${id} processed: ${actionName}`)
    }
  }

  return (
    <UserLayout>
      <div className="space-y-8">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-1.5">
              <MotionBadge text="ACTIVE ANOMALY DETECTIONS" variant="lime" />
            </div>
            <MotionWordReveal
              text="Fraud Alerts & Location Warnings"
              className="text-2xl sm:text-3xl font-medium tracking-tight text-white"
            />
            <p className="mt-1 text-xs text-[#8fa9a6]">
              Real-time alerts generated by deterministic security rules (Velocity, Odd Hours, Unseen Payee, Cross-Border).
            </p>
          </div>

          <div className="flex items-center gap-3">
            <Link
              href="/dashboard/report"
              className="inline-flex items-center gap-2 rounded-xl bg-rose-600 hover:bg-rose-500 px-4 py-2 text-xs font-semibold text-white transition shadow-lg shadow-rose-600/20"
            >
              <ShieldAlert className="size-3.5" /> File New Report
            </Link>
          </div>
        </div>

        {/* ALERT 1: LOCATION + DEVICE ALERT (Prompt Spec 22) */}
        {!resolvedIds.includes('ALERT-101') && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="rounded-2xl border border-rose-500/30 bg-[#0a1718] p-6 space-y-5 shadow-xl shadow-rose-950/20"
          >
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-white/10 pb-4">
              <div className="flex items-center gap-3">
                <div className="p-2.5 rounded-xl bg-rose-500/20 text-rose-400">
                  <AlertOctagon className="size-5" />
                </div>
                <div>
                  <span className="text-[10px] font-bold uppercase tracking-wider text-rose-400">
                    CRITICAL WARNING · 3 CHECKS TRIGGERED
                  </span>
                  <h3 className="text-lg font-bold text-white">LOCATION + DEVICE ALERT</h3>
                </div>
              </div>

              <div className="text-right sm:self-center">
                <p className="text-2xl font-bold text-white font-mono">₹28,000</p>
                <span className="text-[11px] text-[#8fa9a6]">UPI Payment Request</span>
              </div>
            </div>

            {/* Alert Details Grid */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
              <div className="p-3 rounded-xl bg-[#071014] border border-white/5 space-y-1">
                <span className="text-[#8fa9a6]">Receiver VPA</span>
                <p className="font-mono text-white truncate">unknown@upi</p>
                <span className="text-[10px] text-amber-400">New Payee</span>
              </div>

              <div className="p-3 rounded-xl bg-[#071014] border border-white/5 space-y-1">
                <span className="text-[#8fa9a6]">Location</span>
                <p className="font-medium text-white flex items-center gap-1">
                  <MapPin className="size-3 text-rose-400" /> Delhi
                </p>
                <span className="text-[10px] text-rose-400 font-mono">Outside Home Region</span>
              </div>

              <div className="p-3 rounded-xl bg-[#071014] border border-white/5 space-y-1">
                <span className="text-[#8fa9a6]">Device</span>
                <p className="font-medium text-white flex items-center gap-1">
                  <Smartphone className="size-3 text-amber-400" /> New Android
                </p>
                <span className="text-[10px] text-amber-400">Unfingerprinted</span>
              </div>

              <div className="p-3 rounded-xl bg-[#071014] border border-white/5 space-y-1">
                <span className="text-[#8fa9a6]">Time of Attempt</span>
                <p className="font-medium text-white flex items-center gap-1">
                  <Clock className="size-3 text-slate-400" /> 2:18 AM
                </p>
                <span className="text-[10px] text-rose-400">Night Safety Window</span>
              </div>
            </div>

            <div className="p-3.5 rounded-xl bg-rose-500/10 border border-rose-500/20 text-xs text-rose-300 flex items-center gap-2">
              <Info className="size-4 shrink-0" />
              <span>
                Deterministic rules: <strong>NEW_PAYEE_GUARD</strong>, <strong>NIGHT_SAFETY_WINDOW</strong>, and <strong>FOREIGN_DEVICE_TRIGGER</strong> all activated.
              </span>
            </div>

            {/* Actions (Prompt Spec 22) */}
            <div className="flex flex-wrap items-center justify-end gap-3 pt-2">
              <button
                onClick={() => handleAction('ALERT-101', 'Reviewed')}
                className="px-4 py-2 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 text-xs font-semibold text-white transition"
              >
                Review Details
              </button>
              <button
                onClick={() => handleAction('ALERT-101', 'Marked Safe')}
                className="px-4 py-2 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 text-xs font-semibold text-[#b8f55e] transition"
              >
                Mark Safe
              </button>
              <Link
                href="/dashboard/report?upi=unknown@upi&amount=28000"
                className="px-4 py-2 rounded-xl bg-rose-600 hover:bg-rose-500 text-xs font-semibold text-white transition shadow-lg shadow-rose-600/20"
              >
                Report & Dispute
              </Link>
              <button
                onClick={() => handleAction('ALERT-101', 'Account Frozen')}
                className="px-4 py-2 rounded-xl bg-red-950 border border-red-500/40 text-xs font-semibold text-red-200 hover:bg-red-900 transition"
              >
                <Lock className="size-3 inline mr-1" /> Secure Account
              </button>
            </div>
          </motion.div>
        )}

        {/* ALERT 2: INTERNATIONAL LOCATION WARNING (Prompt Spec 55) */}
        {!resolvedIds.includes('ALERT-102') && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="rounded-2xl border border-amber-500/30 bg-[#0a1718] p-6 space-y-5 shadow-xl shadow-amber-950/20"
          >
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-white/10 pb-4">
              <div className="flex items-center gap-3">
                <div className="p-2.5 rounded-xl bg-amber-500/20 text-amber-400">
                  <Globe className="size-5" />
                </div>
                <div>
                  <span className="text-[10px] font-bold uppercase tracking-wider text-amber-400">
                    CROSS-BORDER CARD TRANSACTION WARNING
                  </span>
                  <h3 className="text-lg font-bold text-white">INTERNATIONAL PAYMENT LOCATION</h3>
                </div>
              </div>

              <div className="text-right sm:self-center">
                <p className="text-2xl font-bold text-white font-mono">₹32,000</p>
                <span className="text-[11px] text-[#8fa9a6]">Foreign POS Terminal</span>
              </div>
            </div>

            {/* Alert Details Grid */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
              <div className="p-3 rounded-xl bg-[#071014] border border-white/5 space-y-1">
                <span className="text-[#8fa9a6]">Country</span>
                <p className="font-bold text-white">Singapore (SG)</p>
                <span className="text-[10px] text-amber-400">Non-Resident Terminal</span>
              </div>

              <div className="p-3 rounded-xl bg-[#071014] border border-white/5 space-y-1">
                <span className="text-[#8fa9a6]">Card Used</span>
                <p className="font-mono text-white flex items-center gap-1">
                  <CreditCard className="size-3 text-sky-400" /> **** 4821
                </p>
                <span className="text-[10px] text-sky-400">HDFC Regalia Visa</span>
              </div>

              <div className="p-3 rounded-xl bg-[#071014] border border-white/5 space-y-1">
                <span className="text-[#8fa9a6]">Origin Device</span>
                <p className="font-medium text-white flex items-center gap-1">
                  <Smartphone className="size-3 text-slate-400" /> New / Virtual
                </p>
                <span className="text-[10px] text-slate-400">Apple Pay Gateway</span>
              </div>

              <div className="p-3 rounded-xl bg-[#071014] border border-white/5 space-y-1">
                <span className="text-[#8fa9a6]">Status</span>
                <p className="font-bold text-amber-400">Pending Authorization</p>
                <span className="text-[10px] text-slate-500">Requires Confirmation</span>
              </div>
            </div>

            {/* Actions (Prompt Spec 55) */}
            <div className="flex flex-wrap items-center justify-end gap-3 pt-2">
              <button
                onClick={() => handleAction('ALERT-102', 'Recognized')}
                className="px-4 py-2 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 text-xs font-semibold text-[#b8f55e] transition"
              >
                Recognize
              </button>
              <Link
                href="/dashboard/report?card=4821&amount=32000"
                className="px-4 py-2 rounded-xl bg-rose-600 hover:bg-rose-500 text-xs font-semibold text-white transition shadow-lg shadow-rose-600/20"
              >
                Report Unrecognized
              </Link>
              <button
                onClick={() => handleAction('ALERT-102', 'Card Frozen')}
                className="px-4 py-2 rounded-xl bg-red-950 border border-red-500/40 text-xs font-semibold text-red-200 hover:bg-red-900 transition"
              >
                <Lock className="size-3 inline mr-1" /> Freeze Card
              </button>
            </div>
          </motion.div>
        )}

        {resolvedIds.length >= 2 && (
          <div className="text-center py-16 rounded-2xl border border-white/10 bg-[#0a1718] p-8">
            <CheckCircle2 className="size-12 text-[#b8f55e] mx-auto mb-3" />
            <h3 className="text-lg font-bold text-white">All Security Alerts Acknowledged</h3>
            <p className="text-xs text-[#8fa9a6] mt-1">
              Your account status is currently nominal. Zero active deterministic flags.
            </p>
          </div>
        )}
      </div>

      {/* In-app floating toast for safe non-modal actions */}
      {inAppToast && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: 20 }}
          className="fixed bottom-6 right-6 z-50 rounded-2xl border border-white/15 bg-[#0a1718]/95 px-5 py-3 text-xs font-semibold text-white shadow-2xl backdrop-blur-xl flex items-center gap-2.5"
        >
          <span className="size-2 rounded-full bg-[#b8f55e] animate-ping" />
          <span>{inAppToast}</span>
        </motion.div>
      )}

      {/* Security Action Modal with Further Defensive Actions */}
      <SecurityActionModal
        isOpen={modalConfig.open}
        onClose={() => setModalConfig((prev) => ({ ...prev, open: false }))}
        type={modalConfig.type}
        data={modalConfig.data}
      />
    </UserLayout>
  )
}
